
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  datasource:
    url : jdbc:mariadb://localhost:33601/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1q2w3e4r5t

