
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  datasource:
    #url : jdbc:mariadb://meligo.co.kr:33601/meligoDB
    url : jdbc:mariadb://sagekhw.com:33601/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1q2w3e4r5t

# gateway:
#  ip: 192.168.0.206

order_service:
  # url: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    orders_is_empty: There is no item.
