
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  datasource:
    url : jdbc:mariadb://localhost:33601/meligoDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1q2w3e4r5t

# gateway:
#  ip: 192.168.0.206

order_service:
  # url: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    orders_is_empty: There is no item.
